# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: service.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

from . import service_pb2


class WildosServiceBase(abc.ABC):

    @abc.abstractmethod
    async def SyncUsers(self, stream: 'grpclib.server.Stream[service_pb2.UserData, service_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def RepopulateUsers(self, stream: 'grpclib.server.Stream[service_pb2.UsersData, service_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def FetchBackends(self, stream: 'grpclib.server.Stream[service_pb2.Empty, service_pb2.BackendsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def FetchUsersStats(self, stream: 'grpclib.server.Stream[service_pb2.Empty, service_pb2.UsersStats]') -> None:
        pass

    @abc.abstractmethod
    async def FetchBackendConfig(self, stream: 'grpclib.server.Stream[service_pb2.Backend, service_pb2.BackendConfig]') -> None:
        pass

    @abc.abstractmethod
    async def RestartBackend(self, stream: 'grpclib.server.Stream[service_pb2.RestartBackendRequest, service_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def StreamBackendLogs(self, stream: 'grpclib.server.Stream[service_pb2.BackendLogsRequest, service_pb2.LogLine]') -> None:
        pass

    @abc.abstractmethod
    async def GetBackendStats(self, stream: 'grpclib.server.Stream[service_pb2.Backend, service_pb2.BackendStats]') -> None:
        pass

    @abc.abstractmethod
    async def GetHostSystemMetrics(self, stream: 'grpclib.server.Stream[service_pb2.Empty, service_pb2.HostSystemMetrics]') -> None:
        pass

    @abc.abstractmethod
    async def OpenHostPort(self, stream: 'grpclib.server.Stream[service_pb2.PortActionRequest, service_pb2.PortActionResponse]') -> None:
        pass

    @abc.abstractmethod
    async def CloseHostPort(self, stream: 'grpclib.server.Stream[service_pb2.PortActionRequest, service_pb2.PortActionResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetContainerLogs(self, stream: 'grpclib.server.Stream[service_pb2.ContainerLogsRequest, service_pb2.ContainerLogsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetContainerFiles(self, stream: 'grpclib.server.Stream[service_pb2.ContainerFilesRequest, service_pb2.ContainerFilesResponse]') -> None:
        pass

    @abc.abstractmethod
    async def RestartContainer(self, stream: 'grpclib.server.Stream[service_pb2.Empty, service_pb2.ContainerRestartResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetAllBackendsStats(self, stream: 'grpclib.server.Stream[service_pb2.Empty, service_pb2.AllBackendsStatsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def StreamPeakEvents(self, stream: 'grpclib.server.Stream[service_pb2.Empty, service_pb2.PeakEvent]') -> None:
        pass

    @abc.abstractmethod
    async def FetchPeakEvents(self, stream: 'grpclib.server.Stream[service_pb2.PeakQuery, service_pb2.PeakEvent]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/wildosnode.WildosService/SyncUsers': grpclib.const.Handler(
                self.SyncUsers,
                grpclib.const.Cardinality.STREAM_UNARY,
                service_pb2.UserData,
                service_pb2.Empty,
            ),
            '/wildosnode.WildosService/RepopulateUsers': grpclib.const.Handler(
                self.RepopulateUsers,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.UsersData,
                service_pb2.Empty,
            ),
            '/wildosnode.WildosService/FetchBackends': grpclib.const.Handler(
                self.FetchBackends,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.Empty,
                service_pb2.BackendsResponse,
            ),
            '/wildosnode.WildosService/FetchUsersStats': grpclib.const.Handler(
                self.FetchUsersStats,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.Empty,
                service_pb2.UsersStats,
            ),
            '/wildosnode.WildosService/FetchBackendConfig': grpclib.const.Handler(
                self.FetchBackendConfig,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.Backend,
                service_pb2.BackendConfig,
            ),
            '/wildosnode.WildosService/RestartBackend': grpclib.const.Handler(
                self.RestartBackend,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.RestartBackendRequest,
                service_pb2.Empty,
            ),
            '/wildosnode.WildosService/StreamBackendLogs': grpclib.const.Handler(
                self.StreamBackendLogs,
                grpclib.const.Cardinality.UNARY_STREAM,
                service_pb2.BackendLogsRequest,
                service_pb2.LogLine,
            ),
            '/wildosnode.WildosService/GetBackendStats': grpclib.const.Handler(
                self.GetBackendStats,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.Backend,
                service_pb2.BackendStats,
            ),
            '/wildosnode.WildosService/GetHostSystemMetrics': grpclib.const.Handler(
                self.GetHostSystemMetrics,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.Empty,
                service_pb2.HostSystemMetrics,
            ),
            '/wildosnode.WildosService/OpenHostPort': grpclib.const.Handler(
                self.OpenHostPort,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.PortActionRequest,
                service_pb2.PortActionResponse,
            ),
            '/wildosnode.WildosService/CloseHostPort': grpclib.const.Handler(
                self.CloseHostPort,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.PortActionRequest,
                service_pb2.PortActionResponse,
            ),
            '/wildosnode.WildosService/GetContainerLogs': grpclib.const.Handler(
                self.GetContainerLogs,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.ContainerLogsRequest,
                service_pb2.ContainerLogsResponse,
            ),
            '/wildosnode.WildosService/GetContainerFiles': grpclib.const.Handler(
                self.GetContainerFiles,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.ContainerFilesRequest,
                service_pb2.ContainerFilesResponse,
            ),
            '/wildosnode.WildosService/RestartContainer': grpclib.const.Handler(
                self.RestartContainer,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.Empty,
                service_pb2.ContainerRestartResponse,
            ),
            '/wildosnode.WildosService/GetAllBackendsStats': grpclib.const.Handler(
                self.GetAllBackendsStats,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.Empty,
                service_pb2.AllBackendsStatsResponse,
            ),
            '/wildosnode.WildosService/StreamPeakEvents': grpclib.const.Handler(
                self.StreamPeakEvents,
                grpclib.const.Cardinality.UNARY_STREAM,
                service_pb2.Empty,
                service_pb2.PeakEvent,
            ),
            '/wildosnode.WildosService/FetchPeakEvents': grpclib.const.Handler(
                self.FetchPeakEvents,
                grpclib.const.Cardinality.UNARY_STREAM,
                service_pb2.PeakQuery,
                service_pb2.PeakEvent,
            ),
        }


class WildosServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.SyncUsers = grpclib.client.StreamUnaryMethod(
            channel,
            '/wildosnode.WildosService/SyncUsers',
            service_pb2.UserData,
            service_pb2.Empty,
        )
        self.RepopulateUsers = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wildosnode.WildosService/RepopulateUsers',
            service_pb2.UsersData,
            service_pb2.Empty,
        )
        self.FetchBackends = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wildosnode.WildosService/FetchBackends',
            service_pb2.Empty,
            service_pb2.BackendsResponse,
        )
        self.FetchUsersStats = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wildosnode.WildosService/FetchUsersStats',
            service_pb2.Empty,
            service_pb2.UsersStats,
        )
        self.FetchBackendConfig = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wildosnode.WildosService/FetchBackendConfig',
            service_pb2.Backend,
            service_pb2.BackendConfig,
        )
        self.RestartBackend = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wildosnode.WildosService/RestartBackend',
            service_pb2.RestartBackendRequest,
            service_pb2.Empty,
        )
        self.StreamBackendLogs = grpclib.client.UnaryStreamMethod(
            channel,
            '/wildosnode.WildosService/StreamBackendLogs',
            service_pb2.BackendLogsRequest,
            service_pb2.LogLine,
        )
        self.GetBackendStats = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wildosnode.WildosService/GetBackendStats',
            service_pb2.Backend,
            service_pb2.BackendStats,
        )
        self.GetHostSystemMetrics = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wildosnode.WildosService/GetHostSystemMetrics',
            service_pb2.Empty,
            service_pb2.HostSystemMetrics,
        )
        self.OpenHostPort = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wildosnode.WildosService/OpenHostPort',
            service_pb2.PortActionRequest,
            service_pb2.PortActionResponse,
        )
        self.CloseHostPort = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wildosnode.WildosService/CloseHostPort',
            service_pb2.PortActionRequest,
            service_pb2.PortActionResponse,
        )
        self.GetContainerLogs = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wildosnode.WildosService/GetContainerLogs',
            service_pb2.ContainerLogsRequest,
            service_pb2.ContainerLogsResponse,
        )
        self.GetContainerFiles = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wildosnode.WildosService/GetContainerFiles',
            service_pb2.ContainerFilesRequest,
            service_pb2.ContainerFilesResponse,
        )
        self.RestartContainer = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wildosnode.WildosService/RestartContainer',
            service_pb2.Empty,
            service_pb2.ContainerRestartResponse,
        )
        self.GetAllBackendsStats = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wildosnode.WildosService/GetAllBackendsStats',
            service_pb2.Empty,
            service_pb2.AllBackendsStatsResponse,
        )
        self.StreamPeakEvents = grpclib.client.UnaryStreamMethod(
            channel,
            '/wildosnode.WildosService/StreamPeakEvents',
            service_pb2.Empty,
            service_pb2.PeakEvent,
        )
        self.FetchPeakEvents = grpclib.client.UnaryStreamMethod(
            channel,
            '/wildosnode.WildosService/FetchPeakEvents',
            service_pb2.PeakQuery,
            service_pb2.PeakEvent,
        )
