# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WildosServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SyncUsers = channel.stream_unary(
                '/wildosnode.WildosService/SyncUsers',
                request_serializer=service__pb2.UserData.SerializeToString,
                response_deserializer=service__pb2.Empty.FromString,
                _registered_method=True)
        self.RepopulateUsers = channel.unary_unary(
                '/wildosnode.WildosService/RepopulateUsers',
                request_serializer=service__pb2.UsersData.SerializeToString,
                response_deserializer=service__pb2.Empty.FromString,
                _registered_method=True)
        self.FetchBackends = channel.unary_unary(
                '/wildosnode.WildosService/FetchBackends',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.BackendsResponse.FromString,
                _registered_method=True)
        self.FetchUsersStats = channel.unary_unary(
                '/wildosnode.WildosService/FetchUsersStats',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.UsersStats.FromString,
                _registered_method=True)
        self.FetchBackendConfig = channel.unary_unary(
                '/wildosnode.WildosService/FetchBackendConfig',
                request_serializer=service__pb2.Backend.SerializeToString,
                response_deserializer=service__pb2.BackendConfig.FromString,
                _registered_method=True)
        self.RestartBackend = channel.unary_unary(
                '/wildosnode.WildosService/RestartBackend',
                request_serializer=service__pb2.RestartBackendRequest.SerializeToString,
                response_deserializer=service__pb2.Empty.FromString,
                _registered_method=True)
        self.StreamBackendLogs = channel.unary_stream(
                '/wildosnode.WildosService/StreamBackendLogs',
                request_serializer=service__pb2.BackendLogsRequest.SerializeToString,
                response_deserializer=service__pb2.LogLine.FromString,
                _registered_method=True)
        self.GetBackendStats = channel.unary_unary(
                '/wildosnode.WildosService/GetBackendStats',
                request_serializer=service__pb2.Backend.SerializeToString,
                response_deserializer=service__pb2.BackendStats.FromString,
                _registered_method=True)
        self.GetHostSystemMetrics = channel.unary_unary(
                '/wildosnode.WildosService/GetHostSystemMetrics',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.HostSystemMetrics.FromString,
                _registered_method=True)
        self.OpenHostPort = channel.unary_unary(
                '/wildosnode.WildosService/OpenHostPort',
                request_serializer=service__pb2.PortActionRequest.SerializeToString,
                response_deserializer=service__pb2.PortActionResponse.FromString,
                _registered_method=True)
        self.CloseHostPort = channel.unary_unary(
                '/wildosnode.WildosService/CloseHostPort',
                request_serializer=service__pb2.PortActionRequest.SerializeToString,
                response_deserializer=service__pb2.PortActionResponse.FromString,
                _registered_method=True)
        self.GetContainerLogs = channel.unary_unary(
                '/wildosnode.WildosService/GetContainerLogs',
                request_serializer=service__pb2.ContainerLogsRequest.SerializeToString,
                response_deserializer=service__pb2.ContainerLogsResponse.FromString,
                _registered_method=True)
        self.GetContainerFiles = channel.unary_unary(
                '/wildosnode.WildosService/GetContainerFiles',
                request_serializer=service__pb2.ContainerFilesRequest.SerializeToString,
                response_deserializer=service__pb2.ContainerFilesResponse.FromString,
                _registered_method=True)
        self.RestartContainer = channel.unary_unary(
                '/wildosnode.WildosService/RestartContainer',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.ContainerRestartResponse.FromString,
                _registered_method=True)
        self.GetAllBackendsStats = channel.unary_unary(
                '/wildosnode.WildosService/GetAllBackendsStats',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.AllBackendsStatsResponse.FromString,
                _registered_method=True)
        self.StreamPeakEvents = channel.unary_stream(
                '/wildosnode.WildosService/StreamPeakEvents',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.PeakEvent.FromString,
                _registered_method=True)
        self.FetchPeakEvents = channel.unary_stream(
                '/wildosnode.WildosService/FetchPeakEvents',
                request_serializer=service__pb2.PeakQuery.SerializeToString,
                response_deserializer=service__pb2.PeakEvent.FromString,
                _registered_method=True)


class WildosServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SyncUsers(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RepopulateUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchBackends(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchUsersStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchBackendConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestartBackend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamBackendLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBackendStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHostSystemMetrics(self, request, context):
        """Host system monitoring
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenHostPort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseHostPort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContainerLogs(self, request, context):
        """Container management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContainerFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestartContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllBackendsStats(self, request, context):
        """Batch operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPeakEvents(self, request, context):
        """Peak Monitoring RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchPeakEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WildosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SyncUsers': grpc.stream_unary_rpc_method_handler(
                    servicer.SyncUsers,
                    request_deserializer=service__pb2.UserData.FromString,
                    response_serializer=service__pb2.Empty.SerializeToString,
            ),
            'RepopulateUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.RepopulateUsers,
                    request_deserializer=service__pb2.UsersData.FromString,
                    response_serializer=service__pb2.Empty.SerializeToString,
            ),
            'FetchBackends': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchBackends,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.BackendsResponse.SerializeToString,
            ),
            'FetchUsersStats': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchUsersStats,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.UsersStats.SerializeToString,
            ),
            'FetchBackendConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchBackendConfig,
                    request_deserializer=service__pb2.Backend.FromString,
                    response_serializer=service__pb2.BackendConfig.SerializeToString,
            ),
            'RestartBackend': grpc.unary_unary_rpc_method_handler(
                    servicer.RestartBackend,
                    request_deserializer=service__pb2.RestartBackendRequest.FromString,
                    response_serializer=service__pb2.Empty.SerializeToString,
            ),
            'StreamBackendLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamBackendLogs,
                    request_deserializer=service__pb2.BackendLogsRequest.FromString,
                    response_serializer=service__pb2.LogLine.SerializeToString,
            ),
            'GetBackendStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBackendStats,
                    request_deserializer=service__pb2.Backend.FromString,
                    response_serializer=service__pb2.BackendStats.SerializeToString,
            ),
            'GetHostSystemMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHostSystemMetrics,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.HostSystemMetrics.SerializeToString,
            ),
            'OpenHostPort': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenHostPort,
                    request_deserializer=service__pb2.PortActionRequest.FromString,
                    response_serializer=service__pb2.PortActionResponse.SerializeToString,
            ),
            'CloseHostPort': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseHostPort,
                    request_deserializer=service__pb2.PortActionRequest.FromString,
                    response_serializer=service__pb2.PortActionResponse.SerializeToString,
            ),
            'GetContainerLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContainerLogs,
                    request_deserializer=service__pb2.ContainerLogsRequest.FromString,
                    response_serializer=service__pb2.ContainerLogsResponse.SerializeToString,
            ),
            'GetContainerFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContainerFiles,
                    request_deserializer=service__pb2.ContainerFilesRequest.FromString,
                    response_serializer=service__pb2.ContainerFilesResponse.SerializeToString,
            ),
            'RestartContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.RestartContainer,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.ContainerRestartResponse.SerializeToString,
            ),
            'GetAllBackendsStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllBackendsStats,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.AllBackendsStatsResponse.SerializeToString,
            ),
            'StreamPeakEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPeakEvents,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.PeakEvent.SerializeToString,
            ),
            'FetchPeakEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.FetchPeakEvents,
                    request_deserializer=service__pb2.PeakQuery.FromString,
                    response_serializer=service__pb2.PeakEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wildosnode.WildosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wildosnode.WildosService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WildosService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SyncUsers(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/wildosnode.WildosService/SyncUsers',
            service__pb2.UserData.SerializeToString,
            service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RepopulateUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wildosnode.WildosService/RepopulateUsers',
            service__pb2.UsersData.SerializeToString,
            service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchBackends(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wildosnode.WildosService/FetchBackends',
            service__pb2.Empty.SerializeToString,
            service__pb2.BackendsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchUsersStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wildosnode.WildosService/FetchUsersStats',
            service__pb2.Empty.SerializeToString,
            service__pb2.UsersStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchBackendConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wildosnode.WildosService/FetchBackendConfig',
            service__pb2.Backend.SerializeToString,
            service__pb2.BackendConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestartBackend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wildosnode.WildosService/RestartBackend',
            service__pb2.RestartBackendRequest.SerializeToString,
            service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamBackendLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/wildosnode.WildosService/StreamBackendLogs',
            service__pb2.BackendLogsRequest.SerializeToString,
            service__pb2.LogLine.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBackendStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wildosnode.WildosService/GetBackendStats',
            service__pb2.Backend.SerializeToString,
            service__pb2.BackendStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHostSystemMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wildosnode.WildosService/GetHostSystemMetrics',
            service__pb2.Empty.SerializeToString,
            service__pb2.HostSystemMetrics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenHostPort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wildosnode.WildosService/OpenHostPort',
            service__pb2.PortActionRequest.SerializeToString,
            service__pb2.PortActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseHostPort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wildosnode.WildosService/CloseHostPort',
            service__pb2.PortActionRequest.SerializeToString,
            service__pb2.PortActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContainerLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wildosnode.WildosService/GetContainerLogs',
            service__pb2.ContainerLogsRequest.SerializeToString,
            service__pb2.ContainerLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContainerFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wildosnode.WildosService/GetContainerFiles',
            service__pb2.ContainerFilesRequest.SerializeToString,
            service__pb2.ContainerFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestartContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wildosnode.WildosService/RestartContainer',
            service__pb2.Empty.SerializeToString,
            service__pb2.ContainerRestartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllBackendsStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wildosnode.WildosService/GetAllBackendsStats',
            service__pb2.Empty.SerializeToString,
            service__pb2.AllBackendsStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPeakEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/wildosnode.WildosService/StreamPeakEvents',
            service__pb2.Empty.SerializeToString,
            service__pb2.PeakEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchPeakEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/wildosnode.WildosService/FetchPeakEvents',
            service__pb2.PeakQuery.SerializeToString,
            service__pb2.PeakEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
